### ISSUE TITLE
Improper Token?

### ISSUE THREAD

**Issue by GitHubCrawlers** [Gowixx/indigo-selfbot#3]
←[8;37;100tImproper token has been passed.
Invalid Token
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x039F3EC8>
Traceback (most recent call last):
  File "C:\Users\xannyy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\xannyy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\xannyy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\xannyy\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed but its the right token im confused

**Comment by bytixo** [comment]
pip uninstall discord.py
pip install discord.py-self

**Comment by GitHubCrawlers** [comment]
> pip uninstall discord.py
> pip install discord.py-self

Doesnt work lawl v thanks for trying to help doe

**Comment by GitHubCrawlers** [comment]
> pip uninstall discord.py
> pip install discord.py-self

Nevermind it did

**Comment by Dankongithub** [comment]
At least close the issue

**Comment by Gowixx** [comment]
Closed.
